In [75]:
import pandas as pd 
import numpy as np
from faker import Faker
import datetime
import random
import langdetect

fake = Faker('en_IN')

In [76]:
df = pd.read_csv('../Exampleset/sample_course.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,course_id,url,title,is_paid,instructors,image_480x270,published_title,headline,...,num_published_practice_tests,has_closed_caption,created_at,instructional_level,published_at,objectives_summary,is_recently_published,last_update_date,content_info,category
0,51887,51887,2756550,/course/excel-praktyczny-kurs/,Excel - praktyczny kurs,True,['Norbert Waszak'],https://img-c.udemycdn.com/course/480x270/2756...,excel-praktyczny-kurs,Przyspiesz swoją pracę i zarabiaj więcej.,...,0,False,2020-01-13T13:14:58Z,Beginner Level,2020-01-16T12:31:03Z,['Praktyczny kurs programu Excel'],False,2020-01-14,7 total hours,productivity
1,16794,16794,3723694,/course/igcse-math-0580-practice/,IGCSE Math 0580 Practice,True,['Ahmad Ibrahim'],https://img-c.udemycdn.com/course/480x270/3723...,igcse-math-0580-practice,Solving past paper exams,...,0,True,2020-12-23T14:33:31Z,Intermediate Level,2021-05-08T18:12:56Z,['IGCSE Mathematics 0580 Extended exam practic...,False,2021-04-30,4.5 total hours,teaching
2,2687,2687,610702,/course/simplify/,Minimalism and living 'the minimalist' lifestyle,True,['Jelle Derckx'],https://img-c.udemycdn.com/course/480x270/6107...,simplify,"This is a guide to simplify your life, have le...",...,0,True,2015-09-13T13:06:22Z,All Levels,2015-11-17T20:46:47Z,"['Live with less stress and more focus', 'Know...",False,2015-11-23,1 total hour,personal_development
3,39756,39756,3511170,/course/seo-course-hindi-from-scratch-to-becom...,"Complete SEO Training, Step by Step SEO Course...",True,['Udit Khanna'],https://img-b.udemycdn.com/course/480x270/3511...,seo-course-hindi-from-scratch-to-become-an-expert,"SEO Audit, Keyword Research, OnPage SEO, Schem...",...,0,False,2020-09-19T05:52:11Z,All Levels,2020-09-24T23:18:20Z,['SEO Training on 100+ SEO factors to rank ONE...,False,2020-09-30,30.5 total hours,marketting
4,105660,105660,129572,/course/learn-php-and-mysql-training-course/,Learn PHP and MySQL for Beginners the Easy Way...,True,['Simon Sez IT'],https://img-b.udemycdn.com/course/480x270/1295...,learn-php-and-mysql-training-course,Learn PHP and MySQL and get ready to take your...,...,0,True,2013-12-05T17:06:56Z,Beginner Level,2013-12-31T15:44:15Z,"['By the end of the course, you will have a fo...",False,2021-09-11,12 total hours,development

In [77]:
df.count()

Unnamed: 0.1                    3331
Unnamed: 0                      3331
course_id                       3331
url                             3331
title                           3331
is_paid                         3331
instructors                     3331
image_480x270                   3331
published_title                 3331
headline                        3330
num_subscribers                 3331
avg_rating                      3331
avg_rating_recent               3331
rating                          3331
num_reviews                     3331
num_published_lectures          3331
num_published_practice_tests    3331
has_closed_caption              3331
created_at                      3331
instructional_level             3331
published_at                    3331
objectives_summary              3331
is_recently_published           3331
last_update_date                3326
content_info                    3331
category                        3331
dtype: int64

In [78]:
df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0','url','avg_rating','avg_rating_recent','is_recently_published', \
    'published_at','last_update_date', 'published_title', 'objectives_summary', 'created_at', 'is_paid'])

In [79]:
df.columns = ['course_id','title','instructors','url','headline','num_subscribers', 'rating','num_reviews', \
    'total_lectures','practice_tests','closed_caption','course_level','content_duration','category']

In [80]:
df.head()

,course_id,title,instructors,url,headline,num_subscribers,rating,num_reviews,total_lectures,practice_tests,closed_caption,course_level,content_duration,category
0,2756550,Excel - praktyczny kurs,['Norbert Waszak'],https://img-c.udemycdn.com/course/480x270/2756...,Przyspiesz swoją pracę i zarabiaj więcej.,191,4.739916,37,40,0,False,Beginner Level,7 total hours,productivity
1,3723694,IGCSE Math 0580 Practice,['Ahmad Ibrahim'],https://img-c.udemycdn.com/course/480x270/3723...,Solving past paper exams,21,5.000000,4,37,0,True,Intermediate Level,4.5 total hours,teaching
2,610702,Minimalism and living 'the minimalist' lifestyle,['Jelle Derckx'],https://img-c.udemycdn.com/course/480x270/6107...,"This is a guide to simplify your life, have le...",1459,4.433092,35,24,0,True,All Levels,1 total hour,personal_development
3,3511170,"Complete SEO Training, Step by Step SEO Course...",['Udit Khanna'],https://img-b.udemycdn.com/course/480x270/3511...,"SEO Audit, Keyword Research, OnPage SEO, Schem...",234,4.577489,43,187,0,False,All Levels,30.5 total hours,marketting
4,129572,Learn PHP and MySQL for Beginners the Easy Way...,['Simon Sez IT'],https://img-b.udemycdn.com/course/480x270/1295...,Learn PHP and MySQL and get ready to take your...,3996,3.987829,37,85,0,True,Beginner Level,12 total hours,development

In [81]:
len(df)

3331

In [82]:
published_dates = [fake.date_time_between_dates(datetime.date(2020,1,1), datetime.date(2021,12,31)).strftime('%Y-%m-%d %H:%M:%S') for i in range(len(df))]

In [83]:
# at published date
df['published_date'] = published_dates

In [84]:
def updated_at_fun(row):
    new_date = fake.date_time_between_dates(datetime.date(2022,1,1), datetime.date(2024,1,15)) #.strftime('%Y-%m-%d %H:%M:%S')
    old_date = datetime.datetime.strptime(row, '%Y-%m-%d %H:%M:%S')
    difference_in_days = new_date - old_date
    if difference_in_days.days > 45:
        return new_date.strftime('%Y-%m-%d %H:%M:%S')
    else:
        updated_at_fun(row)

In [85]:
df['last_updated'] = df['published_date'].apply(updated_at_fun)

In [86]:
df['url'] = df['url'].apply(lambda x: x.replace('udemycdn','edtech').replace('udemy','edtech'))

In [87]:
df['price'] = np.random.randint(low=100, high=300, size=len(df))

In [88]:
# options = ['A', 'B', 'C']
# df['New Column'] = random.choices(options, k=len(df))

df['currency'] = random.choice(['USD','INR'])

In [89]:
df['course_price'] = "$ " + df['price'].astype('str') + " " + df['currency']

In [90]:
df['course_language'] = df['title'].apply(lambda x: langdetect.detect(x))

In [91]:
list_s = ['course_id','title','headline','category','course_level','published_date','last_updated','course_price','course_language','total_lectures','content_duration',\
    'closed_caption','practice_tests','instructors','num_subscribers','num_reviews','rating','url']

for i in df.columns:
    if i not in list_s:
        print(i)

price
currency

In [92]:
df = df[list_s]

In [93]:
df.course_language.value_counts()

course_language
en       2445
pt        138
de        129
es        108
ja         68
fr         56
it         43
ca         42
tr         42
no         41
nl         28
ar         26
ru         21
ko         16
tl         15
id         15
ro         14
af         13
da         13
pl          9
sv          8
cy          6
vi          4
bg          4
sl          3
et          3
hr          3
so          3
hi          2
he          2
zh-cn       2
el          1
sw          1
sk          1
mk          1
zh-tw       1
fi          1
ne          1
hu          1
sq          1
Name: count, dtype: int64

In [94]:
def translated_or_not(row):
    if row != 'en':
        return random.choice(['Yes','No','YEs','YES',True,'Ys','NO',False])
    else:
        return random.choice(['Yes','No','YEs','YES',True, 'NO',False])

df['is_translated'] = df['closed_caption'].apply(translated_or_not)

In [95]:
df.head()

,course_id,title,headline,category,course_level,published_date,last_updated,course_price,course_language,total_lectures,content_duration,closed_caption,practice_tests,instructors,num_subscribers,num_reviews,rating,url,is_translated
0,2756550,Excel - praktyczny kurs,Przyspiesz swoją pracę i zarabiaj więcej.,productivity,Beginner Level,2020-02-04 06:34:00,2023-09-23 04:23:36,$ 221 USD,pl,40,7 total hours,False,0,['Norbert Waszak'],191,37,4.739916,https://img-c.edtech.com/course/480x270/275655...,Ys
1,3723694,IGCSE Math 0580 Practice,Solving past paper exams,teaching,Intermediate Level,2020-10-02 08:25:48,2023-12-25 01:26:11,$ 257 USD,en,37,4.5 total hours,True,0,['Ahmad Ibrahim'],21,4,5.000000,https://img-c.edtech.com/course/480x270/372369...,YEs
2,610702,Minimalism and living 'the minimalist' lifestyle,"This is a guide to simplify your life, have le...",personal_development,All Levels,2020-09-22 19:35:09,2023-10-17 02:51:36,$ 190 USD,en,24,1 total hour,True,0,['Jelle Derckx'],1459,35,4.433092,https://img-c.edtech.com/course/480x270/610702...,YEs
3,3511170,"Complete SEO Training, Step by Step SEO Course...","SEO Audit, Keyword Research, OnPage SEO, Schem...",marketting,All Levels,2021-02-06 07:13:27,2023-01-15 14:04:11,$ 229 USD,en,187,30.5 total hours,False,0,['Udit Khanna'],234,43,4.577489,https://img-b.edtech.com/course/480x270/351117...,False
4,129572,Learn PHP and MySQL for Beginners the Easy Way...,Learn PHP and MySQL and get ready to take your...,development,Beginner Level,2021-01-16 15:31:03,2023-01-23 11:02:44,$ 263 USD,en,85,12 total hours,True,0,['Simon Sez IT'],3996,37,3.987829,https://img-b.edtech.com/course/480x270/129572...,True

In [96]:
def translated_language(row):
    if row['is_translated'] in ['Yes','YEs','YES',True,'Ys']:
        if row['course_language']=='en':
            return list(set(random.choices(['es','hi','ru','fr','zh','ja','de','pt',],k=3)))
        else:
            return ['en','hi']
    else:
        return ''
        
    


df['translated_language'] = df.apply(translated_language, axis=1)

In [97]:
df

,course_id,title,headline,category,course_level,published_date,last_updated,course_price,course_language,total_lectures,content_duration,closed_caption,practice_tests,instructors,num_subscribers,num_reviews,rating,url,is_translated,translated_language
0,2756550,Excel - praktyczny kurs,Przyspiesz swoją pracę i zarabiaj więcej.,productivity,Beginner Level,2020-02-04 06:34:00,2023-09-23 04:23:36,$ 221 USD,pl,40,7 total hours,False,0,['Norbert Waszak'],191,37,4.739916,https://img-c.edtech.com/course/480x270/275655...,Ys,"[en, hi]"
1,3723694,IGCSE Math 0580 Practice,Solving past paper exams,teaching,Intermediate Level,2020-10-02 08:25:48,2023-12-25 01:26:11,$ 257 USD,en,37,4.5 total hours,True,0,['Ahmad Ibrahim'],21,4,5.000000,https://img-c.edtech.com/course/480x270/372369...,YEs,"[zh, de, fr]"
2,610702,Minimalism and living 'the minimalist' lifestyle,"This is a guide to simplify your life, have le...",personal_development,All Levels,2020-09-22 19:35:09,2023-10-17 02:51:36,$ 190 USD,en,24,1 total hour,True,0,['Jelle Derckx'],1459,35,4.433092,https://img-c.edtech.com/course/480x270/610702...,YEs,"[de, hi, fr]"
3,3511170,"Complete SEO Training, Step by Step SEO Course...","SEO Audit, Keyword Research, OnPage SEO, Schem...",marketting,All Levels,2021-02-06 07:13:27,2023-01-15 14:04:11,$ 229 USD,en,187,30.5 total hours,False,0,['Udit Khanna'],234,43,4.577489,https://img-b.edtech.com/course/480x270/351117...,False,
4,129572,Learn PHP and MySQL for Beginners the Easy Way...,Learn PHP and MySQL and get ready to take your...,development,Beginner Level,2021-01-16 15:31:03,2023-01-23 11:02:44,$ 263 USD,en,85,12 total hours,True,0,['Simon Sez IT'],3996,37,3.987829,https://img-b.edtech.com/course/480x270/129572...,True,"[ja, ru]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,2237786,Tecniche Avanzate di Fotografia: il Time Blending,Migliora le foto di paesaggio con la tecnica d...,photography,Expert Level,2020-09-24 07:50:03,2022-12-11 14:44:42,$ 139 USD,it,54,5 total hours,False,0,['Mariano Morichini'],372,100,4.724365,https://img-c.edtech.com/course/480x270/223778...,Ys,"[en, hi]"
3327,4493402,Throwing Pottery on the Wheel: How to make cer...,Exploring form and function with the friendlie...,lifestyle,All Levels,2021-01-19 10:51:57,2024-01-04 22:03:21,$ 217 USD,en,8,1 total hour,True,0,['Samuel Deering'],0,0,0.000000,https://img-c.edtech.com/course/480x270/449340...,True,[es]
3328,842728,Getting Started with NodeJS for Beginners,Learn Basic of Powerful JavaScript Engine Node...,development,All Levels,2021-05-23 01:32:31,2022-10-17 21:59:41,$ 247 USD,en,12,1 total hour,True,0,['EDUmobile Academy'],1672,92,4.104616,https://img-c.edtech.com/course/480x270/842728...,No,
3329,4485534,Fit in 5: Lose Weight and Tone Fast! 5 Workout...,Best exercises to shape and lose weight fast!,health_fitness,All Levels,2020-11-05 06:48:22,2023-05-22 20:42:35,$ 204 USD,en,9,37 total mins,True,0,['Kira Langolf'],0,0,0.000000,https://img-b.edtech.com/course/480x270/448553...,True,"[pt, es, fr]"
3330,284506,Edita y crea audios profesionales con Adobe Au...,Edita y Crea audios como los verdaderos expert...,design,All Levels,2021-02-03 05:58:12,2023-03-23 06:02:29,$ 162 USD,es,53,4.5 total hours,True,0,['Pixel Pro Web'],279,66,4.327946,https://img-b.edtech.com/course/480x270/284506...,True,"[en, hi]"

In [98]:
df = df[df['num_subscribers']>0]

In [99]:
len(df)

3233

In [100]:
df.to_csv('./data/course.csv',index=False)

---

In [3]:
# Additional

import pandas as pd 

course_df = pd.read_csv('./data/course.csv')
course_df = course_df[course_df['num_subscribers']>800]

In [4]:
len(course_df)

1308

In [5]:
course_df.head()

,course_id,title,headline,category,course_level,published_date,last_updated,course_price,course_language,total_lectures,content_duration,closed_caption,practice_tests,instructors,num_subscribers,num_reviews,rating,url,is_translated,translated_language
2,610702,Minimalism and living 'the minimalist' lifestyle,"This is a guide to simplify your life, have le...",personal_development,All Levels,2020-09-22 19:35:09,2023-10-17 02:51:36,$ 190 USD,en,24,1 total hour,True,0,['Jelle Derckx'],1459,35,4.433092,https://img-c.edtech.com/course/480x270/610702...,YEs,"['de', 'hi', 'fr']"
4,129572,Learn PHP and MySQL for Beginners the Easy Way...,Learn PHP and MySQL and get ready to take your...,development,Beginner Level,2021-01-16 15:31:03,2023-01-23 11:02:44,$ 263 USD,en,85,12 total hours,True,0,['Simon Sez IT'],3996,37,3.987829,https://img-b.edtech.com/course/480x270/129572...,True,"['ja', 'ru']"
8,1987136,Laravel - Restful API with Passport Authentica...,Learn to create Restful API's and at the same ...,development,Beginner Level,2021-03-11 08:15:43,2022-10-05 09:44:49,$ 132 USD,en,13,1.5 total hours,True,0,"['Edwin Diaz', 'Coding Faculty Solutions']",1348,100,4.563712,https://img-b.edtech.com/course/480x270/198713...,No,NaN
9,1000966,Play Piano 5: Improvise on Misty Eb Key Runs &...,Learn to Improvise with runs and fills on Mist...,music,Expert Level,2021-07-15 04:50:38,2023-01-28 20:56:22,$ 133 USD,en,70,1.5 total hours,False,0,['Rosa Suen'],911,8,4.410278,https://img-c.edtech.com/course/480x270/100096...,False,NaN
15,3549346,MCIA- Mulesoft Certified Integration Architect...,Clear MCIA exam easily after taking this course,software,All Levels,2020-10-07 14:02:08,2022-04-27 13:51:50,$ 111 USD,en,30,10 total hours,True,0,"['Sivaprasad Valluru', 'Rajeswari Yambakam', '...",2616,455,4.454091,https://img-c.edtech.com/course/480x270/354934...,Yes,"['es', 'ja']"

In [6]:
course_df = course_df.drop(columns=['num_subscribers', 'num_reviews','rating'],axis=1)
course_df.head()

,course_id,title,headline,category,course_level,published_date,last_updated,course_price,course_language,total_lectures,content_duration,closed_caption,practice_tests,instructors,url,is_translated,translated_language
2,610702,Minimalism and living 'the minimalist' lifestyle,"This is a guide to simplify your life, have le...",personal_development,All Levels,2020-09-22 19:35:09,2023-10-17 02:51:36,$ 190 USD,en,24,1 total hour,True,0,['Jelle Derckx'],https://img-c.edtech.com/course/480x270/610702...,YEs,"['de', 'hi', 'fr']"
4,129572,Learn PHP and MySQL for Beginners the Easy Way...,Learn PHP and MySQL and get ready to take your...,development,Beginner Level,2021-01-16 15:31:03,2023-01-23 11:02:44,$ 263 USD,en,85,12 total hours,True,0,['Simon Sez IT'],https://img-b.edtech.com/course/480x270/129572...,True,"['ja', 'ru']"
8,1987136,Laravel - Restful API with Passport Authentica...,Learn to create Restful API's and at the same ...,development,Beginner Level,2021-03-11 08:15:43,2022-10-05 09:44:49,$ 132 USD,en,13,1.5 total hours,True,0,"['Edwin Diaz', 'Coding Faculty Solutions']",https://img-b.edtech.com/course/480x270/198713...,No,NaN
9,1000966,Play Piano 5: Improvise on Misty Eb Key Runs &...,Learn to Improvise with runs and fills on Mist...,music,Expert Level,2021-07-15 04:50:38,2023-01-28 20:56:22,$ 133 USD,en,70,1.5 total hours,False,0,['Rosa Suen'],https://img-c.edtech.com/course/480x270/100096...,False,NaN
15,3549346,MCIA- Mulesoft Certified Integration Architect...,Clear MCIA exam easily after taking this course,software,All Levels,2020-10-07 14:02:08,2022-04-27 13:51:50,$ 111 USD,en,30,10 total hours,True,0,"['Sivaprasad Valluru', 'Rajeswari Yambakam', '...",https://img-c.edtech.com/course/480x270/354934...,Yes,"['es', 'ja']"

In [8]:
import datetime
course_df.to_csv(f'./data/courses-{datetime.datetime.today().strftime("%Y-%m-%d")}.csv',index=False)